version: '3'
name: mongo_of_quotes

services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    environment:
      # change these credentials
      MONGO_INITDB_ROOT_USERNAME: mongoadmin 
      MONGO_INITDB_ROOT_PASSWORD: secret
    restart: always
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27888:27017"

  discord_bot:
    container_name: discord_bot
    restart: always
    build:
      context: ./MongoOfQuotes
      dockerfile: Dockerfile
